name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build  --no-daemon
